Auth token
brnvalenca/rest-api-golang pull request #2
Opened 2022-11-01 18:15 UTC by brnvalenca

As transações são feitas por meio de DTO's e tentei ajustar aqueles pontos de atributos das DTO's que haviamos conversado.

2022-11-04 18:07 UTC, joanderencora requested changes
Dei uma primeira olhada com alguns comentários, depois dou outra repassada.

2022-11-04 18:07 UTC, joanderencora commented on services/dogs-serv.go
> +func (dogserv *dserv) CreateDog(d *entities.Dog, b *entities.DogBreed) error {
Geralmente neste receivers, utiliza-se apenas uma letra para representar a variável, tipo: 

```
func (d *dserv)
```
aí nos parametros do método, pode-se colocar um nome maior:
```
CreateDog(dog *entities.Dog, dogBreed *entities.DogBreed)
```

2022-11-04 18:07 UTC, joanderencora commented on services/kennel-serv.go
> +		return err
Não olhei bem o contexto, mas daria para retornar uma lista de erro  no final ao invéz ?

2022-11-07 19:45 UTC, brnvalenca commented on authentication/token.go
> +			if _, ok := token.Claims.(jwt.MapClaims); ok && token.Valid {
Então, caso o token não seja valido em 3 casos ele retorna uma msg de erro
1 - se o token estiver errado ele retorna um error signature
2 - se o token estiver expirado ele retorna um toxen expired
3 - se não houver um token na request ele retorna um not authorized

Por enquanto está desse jeito

2022-11-07 19:46 UTC, brnvalenca commented on controllers/user-controller.go
>  			fmt.Println(err.Error())
Ok, vou fazer isso!

2023-01-02 16:26 UTC, merged